# colors.yaml â€“ System defined colors
# Name: RGB values and whether or not the color works or is intended as a canvas background

# Blues
recycle bin: {r: 131, g: 187, b: 229, canvas: True}
sky: {r: 199, g: 227, b: 245, canvas: True }
blue steel: {r: 159, g: 172, b: 186, canvas: True}
blueprint : {r: 0, g: 77, b: 138, canvas: True}

# Grays
nickel: {r: 146, g: 146, b: 146, canvas: True}
silver: {r: 214, g: 214, b: 214, canvas: True}
magnesium: {r: 192, g: 192, b: 192, canvas: True}
aluminum: {r: 169, g: 169, b: 169, canvas: True}

# Greens
clover: {r: 205, g: 231, b: 178, canvas: True}
institutional: {r: 192, g: 204, b: 160, canvas: True}
olive: {r: 154, g: 152, b: 36, canvas: True}
teal: {r: 125, g: 181, b: 175, canvas: True}
spearmint: {r: 114, g: 183, b: 167, canvas: True}
mint: {r: 87, g: 181, b: 174, canvas: True}

# Yellows
butter: {r: 255, g: 255, b: 191, canvas: True}
limoncello: {r: 255, g: 255, b: 128, canvas: True}
cantaloupe: {r: 255, g: 212, b: 121, canvas: True}
peach: {r: 255, g: 197, b: 95, canvas: True}

# Oranges
pumpkin: {r: 206, g: 124, b: 65, canvas: True}
autumn: {r: 197, g: 150, b: 35, canvas: True}

# Reds
bubble gum: {r: 243, g: 212, b: 222, canvas: True}
pink eraser: {r: 240, g: 176, b: 158, canvas: True}

# Purples
tutti frutti: {r: 246, g: 196, b: 249, canvas: True}
light purple: {r: 237, g: 187, b: 251, canvas: True}
harolds purple crayon: {r: 164, g: 161, b: 211, canvas: True}

# Browns
dead leaf: {r: 180, g: 142, b: 85, canvas: True}

# DIAGNOSTIC COLORS (not suitable for backgrounds)
white: {r: 255, g: 255, b: 255, canvas: False}
black: {r: 0, g: 0, b: 0, canvas: False}
grid blue: {r: 51, g: 235, b: 186, canvas: False}  # To paint the True node grid for diagnostics
purple: {r: 125, g: 51, b: 235, canvas: False}  # Diagnostics for highlighting connectors
horrible red: {r: 255, g: 0, b: 0, canvas: False}  # Used to highlight errors
gold: {r: 255, g: 219, b: 44, canvas: False}  # Used for margin diagnostic

# Logo colors
toyota red: {r: 236, g: 10, b: 30, canvas: False}  # Bright red in TRI logo
block blue: {r: 0, g: 64, b: 128, canvas: False}  # Blue in modelint block titles